status = WARN

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%t] %p %c{1} - %m%n

rootLogger.level = WARN
rootLogger.appenderRef.stdout.ref = STDOUT

logger.spark.name = org.apache.spark
logger.spark.level = WARN

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = WARN